local _M = {}

_M.OPCODE_PRESSUP = 1
_M.OPCODE_PRESSRIGHT = 2;
_M.OPCODE_PRESSDOWN = 3;
_M.OPCODE_PRESSLEFT = 4;
_M.OPCODE_MOVEDIRECTION = 5;
_M.OPCODE_ADDSPEEDUP = 6;
_M.OPCODE_ADDSPEEDDOWN = 7;

return _M