local _M = {}

_M.NONE = 0
_M.PINGHU = 1
_M.DUIDUIHU = 2
_M.QINGYISE = 3
_M.DAIYAOJIU = 4
_M.QIDUI    = 5
_M.JINGOUDIAO = 6
_M.QINGDUIDUI = 7
_M.LONGQIDUI = 8
_M.QINGQIDUI = 9
_M.QINGYAOJIU = 10
_M.JIANGJINGOUDIAO = 11
_M.QINGJINGOUDIAO = 12
_M.TIANHU    = 13
_M.DIHU      = 14
_M.QINGLONGQIDUI = 15
_M.SHIBALUOHAN = 16
_M.QINGSHIBALUOHAN = 17

return _M