local _M = {}

_M.NONE = 0
_M.PINGHU = 1
_M.DUIDUIHU = 2
_M.QINGYISE = 3
_M.QIDUI    = 4
_M.JINGOUDIAO = 5
_M.QINGDUIDUI = 6
_M.LONGQIDUI = 7
_M.QINGQIDUI = 8
_M.QINGJINGOUDIAO = 9
_M.QINGLONGQIDUI = 10
_M.SHIBALUOHAN = 11
_M.QINGSHIBALUOHAN = 12

return _M