root = "./"
thread = 8
logger = nil
logpath = "."
harbor = 1  
address = "127.0.0.1:2428"
master = "127.0.0.1:2015"
start = "main"
bootstrap = "snlua bootstrap"	-- The service for bootstrap
standalone = "0.0.0.0:2015"
luaservice = root.."service/?.lua;"..root.."../login/?.lua"
lualoader = "lualib/loader.lua"
snax = root.."../login/?.lua"
cpath = root.."cservice/?.so"
