root = "./"
thread = 8
logger = nil
logpath = "."
harbor = 1  
address = "127.0.0.1:2428"
master = "127.0.0.1:2013"
start = "main_login"
bootstrap = "snlua bootstrap"	-- The service for bootstrap
standalone = "0.0.0.0:2013"
luaservice = root.."service/?.lua;"..root.."../crazy/?.lua"
lualoader = "lualib/loader.lua"
snax = root.."../crazy/?.lua"
cpath = root.."cservice/?.so"
